defaults:
  -
    values:
      title: HackOn
      tagline: A Virtual Hackathon
      daterange: 11th April 2020 to 19th April 2020
      assets:
        small_logo: './assets/img/GitHub_Logo_White.png'
        logo: './assets/img/GitHub_Logo_White.png'
      socials:
        devfolio: https://platform.hackquarantine.com/
        discord: https://discord.gg/FpgXe8
        platform: https://platform.hackquarantine.com/
        workshops: https://workshops.hackquarantine.com/
        twitter: https://twitter.com/HackQuarantine
        telegram: https://t.me/HackathonHackers

        schedule: /schedule
        emails: 'https://cdn.forms-content.sg-form.com/2e1cc968-66fa-11ea-9912-5e37fcc2990c'
        donate: /donate


collections_dir: _collections

collections:
  - faq
